version: "3"

services:
  openvidu:
    image: openvidu/openvidu-server-kms:2.12.0
    environment:
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=http://192.168.1.101:4443
      - server.ssl.enabled=false
    ports:
      - "4443:4443"
